### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by snifsnsort** [workingDog/scalastix#1]
Hello,
I've tried to install the tool on windows and linux systems. 
Every time i run sbt assemble i get an error that looks like the one below : 

[error] Not a valid command: assemble
[error] Not a valid project ID: assemble
[error] Expected ':'
[error] Not a valid key: assemble (similar: assembly, assemblyJarName, assembleArtifact)
[error] assemble

Is there a way to understand what is missing ? 

Thanks

**Comment by workingDog** [comment]
Hi snifsnsort,

From the error, it looks like you don't have SBT installed.

To be clear what needs to be done to create a fat jar from source:

1) download scalastix library from github, (e.g download zip) and unzip it.

2) install SBT from https://www.scala-sbt.org/
There are some documentations on how to do this for Linux and Windows at:
https://www.scala-sbt.org/1.x/docs/Installing-sbt-on-Windows.html

3) Once SBT is installed, cd to the scalastix directory, then
at a command prompt, type:

sbt assembly

This should create a jar file in the scalastix/target/scala-2.12/ directory.
For example:
scalastix/target/scala-2.12/scalastix-assembly-0.8-SNAPSHOT.jar

Note that scalastix is a library not a tool or application and that java 8 must also be installed.

**Comment by snifsnsort** [comment]
Hi workingDog,
Thanks for your reply. 
I did have the sbt installed on both Linux and windows. 
I tried running it again on windows from the stixload-master root directory .
Here is what i got after few minutes of execution : 
[warn] Found version conflict(s) in library dependencies; some are suspected to be binary incompatible:
[warn]  * com.google.guava:guava:20.0 is selected over 16.0
[warn]      +- com.spotify:docker-client:8.9.0                    (depends on 20.0)
[warn]      +- com.fasterxml.jackson.datatype:jackson-datatype-guava:2.8.8 (depends on 16.0)
[warn]  * org.eclipse.sisu:org.eclipse.sisu.plexus:0.3.2 is selected over 0.0.0.M5
[warn]      +- org.apache.maven:maven-plugin-api:3.3.9            (depends on 0.3.2)
[warn]      +- org.apache.maven:maven-core:3.2.2                  (depends on 0.0.0.M5)
[warn]  * org.codehaus.plexus:plexus-utils:3.0.22 is selected over {1.5.5, 3.0.17}
[warn]      +- org.apache.maven:maven-artifact:3.3.9              (depends on 3.0.22)
[warn]      +- org.apache.maven:maven-model:3.3.9                 (depends on 3.0.22)
[warn]      +- org.eclipse.sisu:org.eclipse.sisu.plexus:0.3.2     (depends on 3.0.17)
[warn]      +- org.apache.maven:maven-settings:3.2.2              (depends on 3.0.17)
[warn]      +- org.apache.maven:maven-repository-metadata:3.2.2   (depends on 3.0.17)
[warn]      +- org.apache.maven:maven-aether-provider:3.2.2       (depends on 3.0.17)
[warn]      +- org.apache.maven:maven-core:3.2.2                  (depends on 3.0.17)
[warn]      +- org.apache.maven:maven-settings-builder:3.2.2      (depends on 3.0.17)
[warn]      +- org.apache.maven:maven-model-builder:3.2.2         (depends on 3.0.17)
[warn]      +- org.sonatype.plexus:plexus-sec-dispatcher:1.3      (depends on 1.5.5)
[warn]  * org.ow2.asm:asm-commons:6.0 is selected over 5.0.3
[warn]      +- org.pantsbuild:jarjar:1.6.5                        (depends on 6.0)
[warn]      +- com.github.jnr:jnr-ffi:2.0.3                       (depends on 5.0.3)
[warn]  * org.ow2.asm:asm-tree:6.0 is selected over 5.0.3
[warn]      +- org.ow2.asm:asm-commons:6.0                        (depends on 6.0)
[warn]      +- com.github.jnr:jnr-ffi:2.0.3                       (depends on 5.0.3)
[warn]      +- org.ow2.asm:asm-util:5.0.3                         (depends on 5.0.3)
[warn]      +- org.ow2.asm:asm-analysis:5.0.3                     (depends on 5.0.3)
[warn]  * org.ow2.asm:asm:6.0 is selected over 5.0.3
[warn]      +- org.pantsbuild:jarjar:1.6.5                        (depends on 6.0)
[warn]      +- org.ow2.asm:asm-tree:6.0                           (depends on 6.0)
[warn]      +- com.github.jnr:jnr-ffi:2.0.3                       (depends on 5.0.3)
[warn] Run 'evicted' to see detailed eviction warnings
[info] Loading settings from build.sbt,sonatype.sbt,version.sbt ...
[info] Set current project to stixloader (in build file:/C:/<......>/stixloader-master/)
[error] Not a valid command: assemble
[error] Not a valid project ID: assemble
[error] Expected ':'
[error] Not a valid key: assemble (similar: assembly, assemblyJarName, assembleArtifact)
[error] assemble
[error]         ^

Any suggestion how to make it work ? 

Thank you

**Comment by workingDog** [comment]
Hi snifsnsort,

I installed Windows 10 on my PC, also installed java 8u171 and sbt 1.1.4.
Ensure that java is in your path.
I downloaded scalastix from github and cd to the scalastix-master directory.
In a command prompt I typed: sbt assembly
and a jar file was produced without any problems.
The first time you use sbt it will take a long time, but after that it should be quick.

Your errors info indicate you are typing assemble not assembly.
Your error info also shows stixloader-master directory.
Are you trying to package stixloader or scalastix?

In any case, can you explain exactly what you downloaded, what system you have (java and sbt installed) 
and what command you use.

**Comment by workingDog** [comment]
Hi snifsnsort,

I have updated sbt setting in scalastix and stixloader projects. 
Could you download the updated projects from github and try again to:

sbt assembly

Let me know if you still have problems.

**Comment by snifsnsort** [comment]
Worked like a charm 

Thank you !!!
